/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.blogspot.chingovan.validator.service.base;

import com.blogspot.chingovan.validator.model.Validator_Student;
import com.blogspot.chingovan.validator.service.Validator_StudentService;
import com.blogspot.chingovan.validator.service.persistence.Validator_StudentPersistence;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.service.BaseServiceImpl;
import com.liferay.portal.service.persistence.UserPersistence;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the validator_ student remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.blogspot.chingovan.validator.service.impl.Validator_StudentServiceImpl}.
 * </p>
 *
 * @author chinv
 * @see com.blogspot.chingovan.validator.service.impl.Validator_StudentServiceImpl
 * @see com.blogspot.chingovan.validator.service.Validator_StudentServiceUtil
 * @generated
 */
public abstract class Validator_StudentServiceBaseImpl extends BaseServiceImpl
	implements Validator_StudentService, IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.blogspot.chingovan.validator.service.Validator_StudentServiceUtil} to access the validator_ student remote service.
	 */

	/**
	 * Returns the validator_ student local service.
	 *
	 * @return the validator_ student local service
	 */
	public com.blogspot.chingovan.validator.service.Validator_StudentLocalService getValidator_StudentLocalService() {
		return validator_StudentLocalService;
	}

	/**
	 * Sets the validator_ student local service.
	 *
	 * @param validator_StudentLocalService the validator_ student local service
	 */
	public void setValidator_StudentLocalService(
		com.blogspot.chingovan.validator.service.Validator_StudentLocalService validator_StudentLocalService) {
		this.validator_StudentLocalService = validator_StudentLocalService;
	}

	/**
	 * Returns the validator_ student remote service.
	 *
	 * @return the validator_ student remote service
	 */
	public com.blogspot.chingovan.validator.service.Validator_StudentService getValidator_StudentService() {
		return validator_StudentService;
	}

	/**
	 * Sets the validator_ student remote service.
	 *
	 * @param validator_StudentService the validator_ student remote service
	 */
	public void setValidator_StudentService(
		com.blogspot.chingovan.validator.service.Validator_StudentService validator_StudentService) {
		this.validator_StudentService = validator_StudentService;
	}

	/**
	 * Returns the validator_ student persistence.
	 *
	 * @return the validator_ student persistence
	 */
	public Validator_StudentPersistence getValidator_StudentPersistence() {
		return validator_StudentPersistence;
	}

	/**
	 * Sets the validator_ student persistence.
	 *
	 * @param validator_StudentPersistence the validator_ student persistence
	 */
	public void setValidator_StudentPersistence(
		Validator_StudentPersistence validator_StudentPersistence) {
		this.validator_StudentPersistence = validator_StudentPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		Class<?> clazz = getClass();

		_classLoader = clazz.getClassLoader();
	}

	public void destroy() {
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	@Override
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	@Override
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	@Override
	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		Thread currentThread = Thread.currentThread();

		ClassLoader contextClassLoader = currentThread.getContextClassLoader();

		if (contextClassLoader != _classLoader) {
			currentThread.setContextClassLoader(_classLoader);
		}

		try {
			return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
		}
		finally {
			if (contextClassLoader != _classLoader) {
				currentThread.setContextClassLoader(contextClassLoader);
			}
		}
	}

	protected Class<?> getModelClass() {
		return Validator_Student.class;
	}

	protected String getModelClassName() {
		return Validator_Student.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = validator_StudentPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = com.blogspot.chingovan.validator.service.Validator_StudentLocalService.class)
	protected com.blogspot.chingovan.validator.service.Validator_StudentLocalService validator_StudentLocalService;
	@BeanReference(type = com.blogspot.chingovan.validator.service.Validator_StudentService.class)
	protected com.blogspot.chingovan.validator.service.Validator_StudentService validator_StudentService;
	@BeanReference(type = Validator_StudentPersistence.class)
	protected Validator_StudentPersistence validator_StudentPersistence;
	@BeanReference(type = com.liferay.counter.service.CounterLocalService.class)
	protected com.liferay.counter.service.CounterLocalService counterLocalService;
	@BeanReference(type = com.liferay.portal.service.ResourceLocalService.class)
	protected com.liferay.portal.service.ResourceLocalService resourceLocalService;
	@BeanReference(type = com.liferay.portal.service.UserLocalService.class)
	protected com.liferay.portal.service.UserLocalService userLocalService;
	@BeanReference(type = com.liferay.portal.service.UserService.class)
	protected com.liferay.portal.service.UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private ClassLoader _classLoader;
	private Validator_StudentServiceClpInvoker _clpInvoker = new Validator_StudentServiceClpInvoker();
}