/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.blogspot.chingovan.validator.service.base;

import com.blogspot.chingovan.validator.model.Validator_Student;
import com.blogspot.chingovan.validator.service.Validator_StudentLocalService;
import com.blogspot.chingovan.validator.service.persistence.Validator_StudentPersistence;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.model.PersistedModel;
import com.liferay.portal.service.BaseLocalServiceImpl;
import com.liferay.portal.service.PersistedModelLocalServiceRegistryUtil;
import com.liferay.portal.service.persistence.UserPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the validator_ student local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.blogspot.chingovan.validator.service.impl.Validator_StudentLocalServiceImpl}.
 * </p>
 *
 * @author chinv
 * @see com.blogspot.chingovan.validator.service.impl.Validator_StudentLocalServiceImpl
 * @see com.blogspot.chingovan.validator.service.Validator_StudentLocalServiceUtil
 * @generated
 */
public abstract class Validator_StudentLocalServiceBaseImpl
	extends BaseLocalServiceImpl implements Validator_StudentLocalService,
		IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.blogspot.chingovan.validator.service.Validator_StudentLocalServiceUtil} to access the validator_ student local service.
	 */

	/**
	 * Adds the validator_ student to the database. Also notifies the appropriate model listeners.
	 *
	 * @param validator_Student the validator_ student
	 * @return the validator_ student that was added
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public Validator_Student addValidator_Student(
		Validator_Student validator_Student) throws SystemException {
		validator_Student.setNew(true);

		return validator_StudentPersistence.update(validator_Student);
	}

	/**
	 * Creates a new validator_ student with the primary key. Does not add the validator_ student to the database.
	 *
	 * @param studentId the primary key for the new validator_ student
	 * @return the new validator_ student
	 */
	@Override
	public Validator_Student createValidator_Student(long studentId) {
		return validator_StudentPersistence.create(studentId);
	}

	/**
	 * Deletes the validator_ student with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param studentId the primary key of the validator_ student
	 * @return the validator_ student that was removed
	 * @throws PortalException if a validator_ student with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public Validator_Student deleteValidator_Student(long studentId)
		throws PortalException, SystemException {
		return validator_StudentPersistence.remove(studentId);
	}

	/**
	 * Deletes the validator_ student from the database. Also notifies the appropriate model listeners.
	 *
	 * @param validator_Student the validator_ student
	 * @return the validator_ student that was removed
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public Validator_Student deleteValidator_Student(
		Validator_Student validator_Student) throws SystemException {
		return validator_StudentPersistence.remove(validator_Student);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(Validator_Student.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery)
		throws SystemException {
		return validator_StudentPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.blogspot.chingovan.validator.model.impl.Validator_StudentModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
		throws SystemException {
		return validator_StudentPersistence.findWithDynamicQuery(dynamicQuery,
			start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.blogspot.chingovan.validator.model.impl.Validator_StudentModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator orderByComparator) throws SystemException {
		return validator_StudentPersistence.findWithDynamicQuery(dynamicQuery,
			start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery)
		throws SystemException {
		return validator_StudentPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery,
		Projection projection) throws SystemException {
		return validator_StudentPersistence.countWithDynamicQuery(dynamicQuery,
			projection);
	}

	@Override
	public Validator_Student fetchValidator_Student(long studentId)
		throws SystemException {
		return validator_StudentPersistence.fetchByPrimaryKey(studentId);
	}

	/**
	 * Returns the validator_ student with the primary key.
	 *
	 * @param studentId the primary key of the validator_ student
	 * @return the validator_ student
	 * @throws PortalException if a validator_ student with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public Validator_Student getValidator_Student(long studentId)
		throws PortalException, SystemException {
		return validator_StudentPersistence.findByPrimaryKey(studentId);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException, SystemException {
		return validator_StudentPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the validator_ students.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.blogspot.chingovan.validator.model.impl.Validator_StudentModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of validator_ students
	 * @param end the upper bound of the range of validator_ students (not inclusive)
	 * @return the range of validator_ students
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public List<Validator_Student> getValidator_Students(int start, int end)
		throws SystemException {
		return validator_StudentPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of validator_ students.
	 *
	 * @return the number of validator_ students
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public int getValidator_StudentsCount() throws SystemException {
		return validator_StudentPersistence.countAll();
	}

	/**
	 * Updates the validator_ student in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param validator_Student the validator_ student
	 * @return the validator_ student that was updated
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public Validator_Student updateValidator_Student(
		Validator_Student validator_Student) throws SystemException {
		return validator_StudentPersistence.update(validator_Student);
	}

	/**
	 * Returns the validator_ student local service.
	 *
	 * @return the validator_ student local service
	 */
	public com.blogspot.chingovan.validator.service.Validator_StudentLocalService getValidator_StudentLocalService() {
		return validator_StudentLocalService;
	}

	/**
	 * Sets the validator_ student local service.
	 *
	 * @param validator_StudentLocalService the validator_ student local service
	 */
	public void setValidator_StudentLocalService(
		com.blogspot.chingovan.validator.service.Validator_StudentLocalService validator_StudentLocalService) {
		this.validator_StudentLocalService = validator_StudentLocalService;
	}

	/**
	 * Returns the validator_ student remote service.
	 *
	 * @return the validator_ student remote service
	 */
	public com.blogspot.chingovan.validator.service.Validator_StudentService getValidator_StudentService() {
		return validator_StudentService;
	}

	/**
	 * Sets the validator_ student remote service.
	 *
	 * @param validator_StudentService the validator_ student remote service
	 */
	public void setValidator_StudentService(
		com.blogspot.chingovan.validator.service.Validator_StudentService validator_StudentService) {
		this.validator_StudentService = validator_StudentService;
	}

	/**
	 * Returns the validator_ student persistence.
	 *
	 * @return the validator_ student persistence
	 */
	public Validator_StudentPersistence getValidator_StudentPersistence() {
		return validator_StudentPersistence;
	}

	/**
	 * Sets the validator_ student persistence.
	 *
	 * @param validator_StudentPersistence the validator_ student persistence
	 */
	public void setValidator_StudentPersistence(
		Validator_StudentPersistence validator_StudentPersistence) {
		this.validator_StudentPersistence = validator_StudentPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		Class<?> clazz = getClass();

		_classLoader = clazz.getClassLoader();

		PersistedModelLocalServiceRegistryUtil.register("com.blogspot.chingovan.validator.model.Validator_Student",
			validator_StudentLocalService);
	}

	public void destroy() {
		PersistedModelLocalServiceRegistryUtil.unregister(
			"com.blogspot.chingovan.validator.model.Validator_Student");
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	@Override
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	@Override
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	@Override
	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		Thread currentThread = Thread.currentThread();

		ClassLoader contextClassLoader = currentThread.getContextClassLoader();

		if (contextClassLoader != _classLoader) {
			currentThread.setContextClassLoader(_classLoader);
		}

		try {
			return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
		}
		finally {
			if (contextClassLoader != _classLoader) {
				currentThread.setContextClassLoader(contextClassLoader);
			}
		}
	}

	protected Class<?> getModelClass() {
		return Validator_Student.class;
	}

	protected String getModelClassName() {
		return Validator_Student.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = validator_StudentPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = com.blogspot.chingovan.validator.service.Validator_StudentLocalService.class)
	protected com.blogspot.chingovan.validator.service.Validator_StudentLocalService validator_StudentLocalService;
	@BeanReference(type = com.blogspot.chingovan.validator.service.Validator_StudentService.class)
	protected com.blogspot.chingovan.validator.service.Validator_StudentService validator_StudentService;
	@BeanReference(type = Validator_StudentPersistence.class)
	protected Validator_StudentPersistence validator_StudentPersistence;
	@BeanReference(type = com.liferay.counter.service.CounterLocalService.class)
	protected com.liferay.counter.service.CounterLocalService counterLocalService;
	@BeanReference(type = com.liferay.portal.service.ResourceLocalService.class)
	protected com.liferay.portal.service.ResourceLocalService resourceLocalService;
	@BeanReference(type = com.liferay.portal.service.UserLocalService.class)
	protected com.liferay.portal.service.UserLocalService userLocalService;
	@BeanReference(type = com.liferay.portal.service.UserService.class)
	protected com.liferay.portal.service.UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private ClassLoader _classLoader;
	private Validator_StudentLocalServiceClpInvoker _clpInvoker = new Validator_StudentLocalServiceClpInvoker();
}