/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.blogspot.chingovan.validator.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Validator_Student service. Represents a row in the &quot;Validator_Student&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.blogspot.chingovan.validator.model.impl.Validator_StudentModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.blogspot.chingovan.validator.model.impl.Validator_StudentImpl}.
 * </p>
 *
 * @author chinv
 * @see Validator_Student
 * @see com.blogspot.chingovan.validator.model.impl.Validator_StudentImpl
 * @see com.blogspot.chingovan.validator.model.impl.Validator_StudentModelImpl
 * @generated
 */
public interface Validator_StudentModel extends BaseModel<Validator_Student> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a validator_ student model instance should use the {@link Validator_Student} interface instead.
	 */

	/**
	 * Returns the primary key of this validator_ student.
	 *
	 * @return the primary key of this validator_ student
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this validator_ student.
	 *
	 * @param primaryKey the primary key of this validator_ student
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the student ID of this validator_ student.
	 *
	 * @return the student ID of this validator_ student
	 */
	public long getStudentId();

	/**
	 * Sets the student ID of this validator_ student.
	 *
	 * @param studentId the student ID of this validator_ student
	 */
	public void setStudentId(long studentId);

	/**
	 * Returns the code of this validator_ student.
	 *
	 * @return the code of this validator_ student
	 */
	@AutoEscape
	public String getCode();

	/**
	 * Sets the code of this validator_ student.
	 *
	 * @param code the code of this validator_ student
	 */
	public void setCode(String code);

	/**
	 * Returns the fullname of this validator_ student.
	 *
	 * @return the fullname of this validator_ student
	 */
	@AutoEscape
	public String getFullname();

	/**
	 * Sets the fullname of this validator_ student.
	 *
	 * @param fullname the fullname of this validator_ student
	 */
	public void setFullname(String fullname);

	/**
	 * Returns the gender of this validator_ student.
	 *
	 * @return the gender of this validator_ student
	 */
	public boolean getGender();

	/**
	 * Returns <code>true</code> if this validator_ student is gender.
	 *
	 * @return <code>true</code> if this validator_ student is gender; <code>false</code> otherwise
	 */
	public boolean isGender();

	/**
	 * Sets whether this validator_ student is gender.
	 *
	 * @param gender the gender of this validator_ student
	 */
	public void setGender(boolean gender);

	/**
	 * Returns the birthday of this validator_ student.
	 *
	 * @return the birthday of this validator_ student
	 */
	public Date getBirthday();

	/**
	 * Sets the birthday of this validator_ student.
	 *
	 * @param birthday the birthday of this validator_ student
	 */
	public void setBirthday(Date birthday);

	/**
	 * Returns the email of this validator_ student.
	 *
	 * @return the email of this validator_ student
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this validator_ student.
	 *
	 * @param email the email of this validator_ student
	 */
	public void setEmail(String email);

	/**
	 * Returns the address of this validator_ student.
	 *
	 * @return the address of this validator_ student
	 */
	@AutoEscape
	public String getAddress();

	/**
	 * Sets the address of this validator_ student.
	 *
	 * @param address the address of this validator_ student
	 */
	public void setAddress(String address);

	/**
	 * Returns the blog of this validator_ student.
	 *
	 * @return the blog of this validator_ student
	 */
	@AutoEscape
	public String getBlog();

	/**
	 * Sets the blog of this validator_ student.
	 *
	 * @param blog the blog of this validator_ student
	 */
	public void setBlog(String blog);

	/**
	 * Returns the mark of this validator_ student.
	 *
	 * @return the mark of this validator_ student
	 */
	public double getMark();

	/**
	 * Sets the mark of this validator_ student.
	 *
	 * @param mark the mark of this validator_ student
	 */
	public void setMark(double mark);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.blogspot.chingovan.validator.model.Validator_Student validator_Student);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.blogspot.chingovan.validator.model.Validator_Student> toCacheModel();

	@Override
	public com.blogspot.chingovan.validator.model.Validator_Student toEscapedModel();

	@Override
	public com.blogspot.chingovan.validator.model.Validator_Student toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}