/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.blogspot.chingovan.validator.model.impl;

import com.blogspot.chingovan.validator.model.Validator_Student;
import com.blogspot.chingovan.validator.model.Validator_StudentModel;
import com.blogspot.chingovan.validator.model.Validator_StudentSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Validator_Student service. Represents a row in the &quot;Validator_Student&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.blogspot.chingovan.validator.model.Validator_StudentModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link Validator_StudentImpl}.
 * </p>
 *
 * @author chinv
 * @see Validator_StudentImpl
 * @see com.blogspot.chingovan.validator.model.Validator_Student
 * @see com.blogspot.chingovan.validator.model.Validator_StudentModel
 * @generated
 */
@JSON(strict = true)
public class Validator_StudentModelImpl extends BaseModelImpl<Validator_Student>
	implements Validator_StudentModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a validator_ student model instance should use the {@link com.blogspot.chingovan.validator.model.Validator_Student} interface instead.
	 */
	public static final String TABLE_NAME = "Validator_Student";
	public static final Object[][] TABLE_COLUMNS = {
			{ "StudentId", Types.BIGINT },
			{ "Code", Types.VARCHAR },
			{ "Fullname", Types.VARCHAR },
			{ "Gender", Types.BOOLEAN },
			{ "Birthday", Types.TIMESTAMP },
			{ "Email", Types.VARCHAR },
			{ "Address", Types.VARCHAR },
			{ "Blog", Types.VARCHAR },
			{ "Mark", Types.DOUBLE }
		};
	public static final String TABLE_SQL_CREATE = "create table Validator_Student (StudentId LONG not null primary key,Code VARCHAR(75) null,Fullname VARCHAR(75) null,Gender BOOLEAN,Birthday DATE null,Email VARCHAR(75) null,Address VARCHAR(75) null,Blog VARCHAR(75) null,Mark DOUBLE)";
	public static final String TABLE_SQL_DROP = "drop table Validator_Student";
	public static final String ORDER_BY_JPQL = " ORDER BY validator_Student.studentId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY Validator_Student.StudentId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.blogspot.chingovan.validator.model.Validator_Student"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.blogspot.chingovan.validator.model.Validator_Student"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Validator_Student toModel(Validator_StudentSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Validator_Student model = new Validator_StudentImpl();

		model.setStudentId(soapModel.getStudentId());
		model.setCode(soapModel.getCode());
		model.setFullname(soapModel.getFullname());
		model.setGender(soapModel.getGender());
		model.setBirthday(soapModel.getBirthday());
		model.setEmail(soapModel.getEmail());
		model.setAddress(soapModel.getAddress());
		model.setBlog(soapModel.getBlog());
		model.setMark(soapModel.getMark());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Validator_Student> toModels(
		Validator_StudentSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Validator_Student> models = new ArrayList<Validator_Student>(soapModels.length);

		for (Validator_StudentSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.blogspot.chingovan.validator.model.Validator_Student"));

	public Validator_StudentModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _studentId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setStudentId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _studentId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Validator_Student.class;
	}

	@Override
	public String getModelClassName() {
		return Validator_Student.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("studentId", getStudentId());
		attributes.put("code", getCode());
		attributes.put("fullname", getFullname());
		attributes.put("gender", getGender());
		attributes.put("birthday", getBirthday());
		attributes.put("email", getEmail());
		attributes.put("address", getAddress());
		attributes.put("blog", getBlog());
		attributes.put("mark", getMark());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long studentId = (Long)attributes.get("studentId");

		if (studentId != null) {
			setStudentId(studentId);
		}

		String code = (String)attributes.get("code");

		if (code != null) {
			setCode(code);
		}

		String fullname = (String)attributes.get("fullname");

		if (fullname != null) {
			setFullname(fullname);
		}

		Boolean gender = (Boolean)attributes.get("gender");

		if (gender != null) {
			setGender(gender);
		}

		Date birthday = (Date)attributes.get("birthday");

		if (birthday != null) {
			setBirthday(birthday);
		}

		String email = (String)attributes.get("email");

		if (email != null) {
			setEmail(email);
		}

		String address = (String)attributes.get("address");

		if (address != null) {
			setAddress(address);
		}

		String blog = (String)attributes.get("blog");

		if (blog != null) {
			setBlog(blog);
		}

		Double mark = (Double)attributes.get("mark");

		if (mark != null) {
			setMark(mark);
		}
	}

	@JSON
	@Override
	public long getStudentId() {
		return _studentId;
	}

	@Override
	public void setStudentId(long studentId) {
		_studentId = studentId;
	}

	@JSON
	@Override
	public String getCode() {
		if (_code == null) {
			return StringPool.BLANK;
		}
		else {
			return _code;
		}
	}

	@Override
	public void setCode(String code) {
		_code = code;
	}

	@JSON
	@Override
	public String getFullname() {
		if (_fullname == null) {
			return StringPool.BLANK;
		}
		else {
			return _fullname;
		}
	}

	@Override
	public void setFullname(String fullname) {
		_fullname = fullname;
	}

	@JSON
	@Override
	public boolean getGender() {
		return _gender;
	}

	@Override
	public boolean isGender() {
		return _gender;
	}

	@Override
	public void setGender(boolean gender) {
		_gender = gender;
	}

	@JSON
	@Override
	public Date getBirthday() {
		return _birthday;
	}

	@Override
	public void setBirthday(Date birthday) {
		_birthday = birthday;
	}

	@JSON
	@Override
	public String getEmail() {
		if (_email == null) {
			return StringPool.BLANK;
		}
		else {
			return _email;
		}
	}

	@Override
	public void setEmail(String email) {
		_email = email;
	}

	@JSON
	@Override
	public String getAddress() {
		if (_address == null) {
			return StringPool.BLANK;
		}
		else {
			return _address;
		}
	}

	@Override
	public void setAddress(String address) {
		_address = address;
	}

	@JSON
	@Override
	public String getBlog() {
		if (_blog == null) {
			return StringPool.BLANK;
		}
		else {
			return _blog;
		}
	}

	@Override
	public void setBlog(String blog) {
		_blog = blog;
	}

	@JSON
	@Override
	public double getMark() {
		return _mark;
	}

	@Override
	public void setMark(double mark) {
		_mark = mark;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			Validator_Student.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Validator_Student toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Validator_Student)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		Validator_StudentImpl validator_StudentImpl = new Validator_StudentImpl();

		validator_StudentImpl.setStudentId(getStudentId());
		validator_StudentImpl.setCode(getCode());
		validator_StudentImpl.setFullname(getFullname());
		validator_StudentImpl.setGender(getGender());
		validator_StudentImpl.setBirthday(getBirthday());
		validator_StudentImpl.setEmail(getEmail());
		validator_StudentImpl.setAddress(getAddress());
		validator_StudentImpl.setBlog(getBlog());
		validator_StudentImpl.setMark(getMark());

		validator_StudentImpl.resetOriginalValues();

		return validator_StudentImpl;
	}

	@Override
	public int compareTo(Validator_Student validator_Student) {
		long primaryKey = validator_Student.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Validator_Student)) {
			return false;
		}

		Validator_Student validator_Student = (Validator_Student)obj;

		long primaryKey = validator_Student.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<Validator_Student> toCacheModel() {
		Validator_StudentCacheModel validator_StudentCacheModel = new Validator_StudentCacheModel();

		validator_StudentCacheModel.studentId = getStudentId();

		validator_StudentCacheModel.code = getCode();

		String code = validator_StudentCacheModel.code;

		if ((code != null) && (code.length() == 0)) {
			validator_StudentCacheModel.code = null;
		}

		validator_StudentCacheModel.fullname = getFullname();

		String fullname = validator_StudentCacheModel.fullname;

		if ((fullname != null) && (fullname.length() == 0)) {
			validator_StudentCacheModel.fullname = null;
		}

		validator_StudentCacheModel.gender = getGender();

		Date birthday = getBirthday();

		if (birthday != null) {
			validator_StudentCacheModel.birthday = birthday.getTime();
		}
		else {
			validator_StudentCacheModel.birthday = Long.MIN_VALUE;
		}

		validator_StudentCacheModel.email = getEmail();

		String email = validator_StudentCacheModel.email;

		if ((email != null) && (email.length() == 0)) {
			validator_StudentCacheModel.email = null;
		}

		validator_StudentCacheModel.address = getAddress();

		String address = validator_StudentCacheModel.address;

		if ((address != null) && (address.length() == 0)) {
			validator_StudentCacheModel.address = null;
		}

		validator_StudentCacheModel.blog = getBlog();

		String blog = validator_StudentCacheModel.blog;

		if ((blog != null) && (blog.length() == 0)) {
			validator_StudentCacheModel.blog = null;
		}

		validator_StudentCacheModel.mark = getMark();

		return validator_StudentCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(19);

		sb.append("{studentId=");
		sb.append(getStudentId());
		sb.append(", code=");
		sb.append(getCode());
		sb.append(", fullname=");
		sb.append(getFullname());
		sb.append(", gender=");
		sb.append(getGender());
		sb.append(", birthday=");
		sb.append(getBirthday());
		sb.append(", email=");
		sb.append(getEmail());
		sb.append(", address=");
		sb.append(getAddress());
		sb.append(", blog=");
		sb.append(getBlog());
		sb.append(", mark=");
		sb.append(getMark());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(31);

		sb.append("<model><model-name>");
		sb.append("com.blogspot.chingovan.validator.model.Validator_Student");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>studentId</column-name><column-value><![CDATA[");
		sb.append(getStudentId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>code</column-name><column-value><![CDATA[");
		sb.append(getCode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fullname</column-name><column-value><![CDATA[");
		sb.append(getFullname());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>gender</column-name><column-value><![CDATA[");
		sb.append(getGender());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>birthday</column-name><column-value><![CDATA[");
		sb.append(getBirthday());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>email</column-name><column-value><![CDATA[");
		sb.append(getEmail());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>address</column-name><column-value><![CDATA[");
		sb.append(getAddress());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>blog</column-name><column-value><![CDATA[");
		sb.append(getBlog());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>mark</column-name><column-value><![CDATA[");
		sb.append(getMark());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = Validator_Student.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			Validator_Student.class
		};
	private long _studentId;
	private String _code;
	private String _fullname;
	private boolean _gender;
	private Date _birthday;
	private String _email;
	private String _address;
	private String _blog;
	private double _mark;
	private Validator_Student _escapedModel;
}